service: py-aws-lambda-thumbnail-gen

custom:
  stage: ${opt:stage, self:provider.stage}
  srcBucket: 
    'Fn::ImportValue': '${self:custom.stage}-UploadBucketName'
  snsTopicArn: 
    'Fn::ImportValue': '${self:custom.stage}-RecoDoneSNSTopicArn'
  snsTopicName:
    'Fn::ImportValue': '${self:custom.stage}-RecoDoneSNSTopicName'

provider:
  name: aws
  # Python 3.6 (not 3.7) required for ML model execution
  runtime: python3.6
  stage: dev
  region: eu-west-1
  memorySize: 512
  timeout: 10

  # WARNING: this is a very permissive policy
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
        - "lambda:GetLayerVersion"
        - "lambda:GetLayerVersionPolicy"
        - "s3:*"
        - "sns:*"
        - "dynamodb:*"
      Resource: "*"

functions:
  py-aws-lambda-thumbnail-gen:
    handler: lambda_function.lambda_handler
    events:
    - sns: ${cf:py-aws-lambda-image-reco-dev.RecoDoneSNSTopicArn}

#      - sns: ${cf:py-aws-lambda-image-reco-dev.RecoDoneSNSTopicArn}

# arn:aws:sns:eu-west-1:814098365754:py-aws-lambda-image-reco-dev-serverless-reco-results
    environment:
      imgSrcBucket: 
        'Fn::ImportValue': '${self:custom.stage}-UploadBucketName' 
      thumbDestBucket: 
        Ref: MyThumbDestBucket
      bucket_dummy: 
        ${self:custom.srcBucket}
      snsTopicArn_dummy:
        ${self:custom.snsTopicArn}
      snsTopicName_dummy:
        ${self:custom.snsTopicName}
     
resources:
  Resources:
    # Naming convention (S3Bucket<resource-name> seems important to be alloweed to configure event later)
    # See https://github.com/serverless/serverless/issues/4194#issuecomment-455568672
    MyThumbDestBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.stage}-thumb-dest-bucket
        # Set the CORS policy
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
              AllowedMethods:
                - POST
              MaxAge: 3000