service: awstacktraining-uploads

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-1

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        # BucketName: ${self:custom.stage}-uploadbucketestodm
        # Set the CORS policy
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - POST
              MaxAge: 3000

  # Print out the name of the bucket that is created
  Outputs:
    UploadBucketArn:
      Value:
         Fn::GetAtt:
          - S3Bucket
          - Arn
      Export:
        Name: ${self:custom.stage}-UploadBucketArn

    UploadBucketName:
      Value:
        Ref: S3Bucket
      Export:
        Name: ${self:custom.stage}-UploadBucket